channels:
    - conda-forge
    - defaults
dependencies:
    - pip
    - bumpversion
    - wheel
    - watchdog
    - flake8
    - tox
    - coverage
    - Sphinx
    - twine
    - pytest
    - pytest-runner
    - pytest-cov
{% if cookiecutter.add_git_pre_commit_hook_isort == 'y'
      or cookiecutter.add_git_pre_commit_hook_black == 'y'
      or cookiecutter.add_git_pre_commit_hook_flake8 == 'y'
      or cookiecutter.add_git_pre_commit_hook_mypy == 'y'
%}    - pre-commit{% endif %}
